// Get individual alert for all cameras - with search (camera name, location, alert name, alert type) and pagination
// GET - api/v1/alert/
// [
// 	{
// 		"cameraId": "",
// 		"cameraName": "",
// 		"x-coordinates": ,
// 		"y-coordinates": ,
// 		"cameraAngle": 0, 90, 180, 270, 360
// 		"fieldOfView": 0, 90, 180, 270, 360
// 		"location", "",
// 		"alertType": "",
// 		"alertName": "",
// 		"alertId": "",
// 		"timestamp": epochtime (utc)
// 		"status": resolved / unresolved
// 		"videoClipUrl": "",
// 		"images": [ "", "", "", "" ],
// 		"liveFeedUrl": ""
// 	}
// ]

export const alertsMockData = [
    {
        "cameraId": "C001",
        "cameraName": "Front Entrance",
        "x-coordinates": 50,
        "y-coordinates": 150,
        "cameraAngle": 0,
        "fieldOfView": 90,
        "location": "Building A",
        "alertType": "PPE no helmet",
        "alertName": "Helmet Missing",
        "alertId": "1",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video1.mp4",
        "images": ["http://example.com/image1.jpg", "http://example.com/image2.jpg", "http://example.com/image3.jpg", "http://example.com/image4.jpg"],
        "liveFeedUrl": "http://example.com/livefeed1"
    },
    {
        "cameraId": "C002",
        "cameraName": "Side Entrance",
        "x-coordinates": 200,
        "y-coordinates": 300,
        "cameraAngle": 90,
        "fieldOfView": 180,
        "location": "Building B",
        "alertType": "Unauthorized access",
        "alertName": "Unauthorized Access",
        "alertId": "2",
        "timestamp": 1699478400000,
        "status": "unresolved",
        "videoClipUrl": "http://example.com/video2.mp4",
        "images": ["http://example.com/image5.jpg", "http://example.com/image6.jpg", "http://example.com/image7.jpg", "http://example.com/image8.jpg"],
        "liveFeedUrl": "http://example.com/livefeed2"
    },
    {
        "cameraId": "C003",
        "cameraName": "Back Entrance",
        "x-coordinates": 350,
        "y-coordinates": 400,
        "cameraAngle": 180,
        "fieldOfView": 270,
        "location": "Building C",
        "alertType": "Fire alarm triggered",
        "alertName": "Fire Alarm Triggered",
        "alertId": "3",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video3.mp4",
        "images": ["http://example.com/image9.jpg", "http://example.com/image10.jpg", "http://example.com/image11.jpg", "http://example.com/image12.jpg"],
        "liveFeedUrl": "http://example.com/livefeed3"
    },
    {
        "cameraId": "C004",
        "cameraName": "Loading Dock",
        "x-coordinates": 100,
        "y-coordinates": 500,
        "cameraAngle": 270,
        "fieldOfView": 360,
        "location": "Building D",
        "alertType": "Gas leak detected",
        "alertName": "Gas Leak Detected",
        "alertId": "4",
        "timestamp": 1699478400000,
        "status": "unresolved",
        "videoClipUrl": "http://example.com/video4.mp4",
        "images": ["http://example.com/image13.jpg", "http://example.com/image14.jpg", "http://example.com/image15.jpg", "http://example.com/image16.jpg"],
        "liveFeedUrl": "http://example.com/livefeed4"
    },
    {
        "cameraId": "C005",
        "cameraName": "Warehouse A",
        "x-coordinates": 250,
        "y-coordinates": 600,
        "cameraAngle": 360,
        "fieldOfView": 90,
        "location": "Building E",
        "alertType": "Machine malfunction",
        "alertName": "Machine Malfunction",
        "alertId": "5",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video5.mp4",
        "images": ["http://example.com/image17.jpg", "http://example.com/image18.jpg", "http://example.com/image19.jpg", "http://example.com/image20.jpg"],
        "liveFeedUrl": "http://example.com/livefeed5"
    },
    {
        "cameraId": "C006",
        "cameraName": "Warehouse B",
        "x-coordinates": 400,
        "y-coordinates": 700,
        "cameraAngle": 90,
        "fieldOfView": 180,
        "location": "Building F",
        "alertType": "Prohibited area entry",
        "alertName": "Prohibited Area Entry",
        "alertId": "6",
        "timestamp": 1699478400000,
        "status": "unresolved",
        "videoClipUrl": "http://example.com/video6.mp4",
        "images": ["http://example.com/image21.jpg", "http://example.com/image22.jpg", "http://example.com/image23.jpg", "http://example.com/image24.jpg"],
        "liveFeedUrl": "http://example.com/livefeed6"
    },
    {
        "cameraId": "C007",
        "cameraName": "Main Office",
        "x-coordinates": 150,
        "y-coordinates": 250,
        "cameraAngle": 0,
        "fieldOfView": 90,
        "location": "Building G",
        "alertType": "High noise level",
        "alertName": "High Noise Level",
        "alertId": "7",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video7.mp4",
        "images": ["http://example.com/image25.jpg", "http://example.com/image26.jpg", "http://example.com/image27.jpg", "http://example.com/image28.jpg"],
        "liveFeedUrl": "http://example.com/livefeed7"
    },
    {
        "cameraId": "C008",
        "cameraName": "Parking Lot",
        "x-coordinates": 300,
        "y-coordinates": 350,
        "cameraAngle": 180,
        "fieldOfView": 270,
        "location": "Building H",
        "alertType": "Slip or trip hazard",
        "alertName": "Slip or Trip Hazard",
        "alertId": "8",
        "timestamp": 1699478400000,
        "status": "unresolved",
        "videoClipUrl": "http://example.com/video8.mp4",
        "images": ["http://example.com/image29.jpg", "http://example.com/image30.jpg", "http://example.com/image31.jpg", "http://example.com/image32.jpg"],
        "liveFeedUrl": "http://example.com/livefeed8"
    },
    {
        "cameraId": "C009",
        "cameraName": "R&D Lab",
        "x-coordinates": 450,
        "y-coordinates": 400,
        "cameraAngle": 270,
        "fieldOfView": 360,
        "location": "Building I",
        "alertType": "Temperature out of range",
        "alertName": "Temperature Out of Range",
        "alertId": "9",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video9.mp4",
        "images": ["http://example.com/image33.jpg", "http://example.com/image34.jpg", "http://example.com/image35.jpg", "http://example.com/image36.jpg"],
        "liveFeedUrl": "http://example.com/livefeed9"
    },
    {
        "cameraId": "C010",
        "cameraName": "Conference Room",
        "x-coordinates": 100,
        "y-coordinates": 200,
        "cameraAngle": 360,
        "fieldOfView": 90,
        "location": "Building J",
        "alertType": "Fall detection",
        "alertName": "Fall Detection",
        "alertId": "10",
        "timestamp": 1699478400000,
        "status": "unresolved",
        "videoClipUrl": "http://example.com/video10.mp4",
        "images": ["http://example.com/image37.jpg", "http://example.com/image38.jpg", "http://example.com/image39.jpg", "http://example.com/image40.jpg"],
        "liveFeedUrl": "http://example.com/livefeed10"
    },
    {
        "cameraId": "C011",
        "cameraName": "Break Room",
        "x-coordinates": 250,
        "y-coordinates": 100,
        "cameraAngle": 90,
        "fieldOfView": 180,
        "location": "Building K",
        "alertType": "Insecure equipment",
        "alertName": "Insecure Equipment",
        "alertId": "11",
        "timestamp": 1699478400000,
        "status": "resolved",
        "videoClipUrl": "http://example.com/video11.mp4",
        "images": ["http://example.com/image41.jpg", "http://example.com/image42.jpg", "http://example.com/image43.jpg", "http://example.com/image44.jpg"],
        "liveFeedUrl": "http://example.com/livefeed11"
    }
]